DELETE FROM ANIMAL;
DELETE FROM ESPECIE;
DELETE FROM TIPO_ANIMAL;

INSERT INTO TIPO_ANIMAL (ACRONIMO, NOME) VALUES ('CAO', 'Cachorro');
INSERT INTO TIPO_ANIMAL (ACRONIMO, NOME) VALUES ('GAT', 'Gato');

INSERT INTO ESPECIE (NOME, DESCRICAO, TIPO_ANIMAL_ACRONIMO) VALUES ('Cachorro Comum', 'Um tipo de cachorro vira-latas', 'CAO');
INSERT INTO ESPECIE (NOME, DESCRICAO, TIPO_ANIMAL_ACRONIMO) VALUES ('Gato Comum', 'Um tipo de gato', 'GAT');

INSERT INTO ANIMAL (ESPECIE_ID, NOME, NASCIMENTO)
SELECT ESPECIE.ID, 'Totó', to_date('01/01/2013', 'DD/MM/YYYY') FROM ESPECIE
WHERE ESPECIE.NOME = 'Cachorro Comum';

INSERT INTO ANIMAL (ESPECIE_ID, NOME, NASCIMENTO)
SELECT ESPECIE.ID, 'Bichano', to_date('01/01/2012', 'DD/MM/YYYY') FROM ESPECIE
WHERE ESPECIE.NOME = 'Gato Comum';

INSERT INTO ANIMAL (ESPECIE_ID, NOME, NASCIMENTO)
SELECT ESPECIE.ID, 'Tom', to_date('01/01/2015', 'DD/MM/YYYY') FROM ESPECIE
WHERE ESPECIE.NOME = 'Gato Comum';

INSERT INTO ANIMAL (ESPECIE_ID, NOME, NASCIMENTO)
SELECT ESPECIE.ID, 'Gatuno', to_date('01/01/2011', 'DD/MM/YYYY') FROM ESPECIE
WHERE ESPECIE.NOME = 'Gato Comum';